GET http://localhost:5000/pemilik

###
GET http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e

###
POST http://localhost:5000/pemilik
Content-Type: application/json

{
    "nama": "Yanuar Fauzan",
    "email": "yanuarisnain017@gmail.com",
    "alamat": "bumi"
}

###
PATCH http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e
Content-Type: application/json

{
    "nama": "Yanuar Fauzan",
    "email": "yanuarisnain017@gmail.com",
    "alamat": "bumi kita berdua"
}

###
DELETE http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e


###
GET http://localhost:5000/kategori

###
GET http://localhost:5000/kategori/64741b9f1e88ccc897a75bc4


###
POST http://localhost:5000/kategori
Content-Type: application/json

{
    "nama_kategori": "Drama Comedy"
}

###
PATCH http://localhost:5000/kategori/64741b9f1e88ccc897a75bc4
Content-Type: application/json

{
    "nama_kategori": "Drama Gelay"
}

###
DELETE http://localhost:5000/kategori/64741b9f1e88ccc897a75bc4


