GET http://localhost:5000/pemilik

###
GET http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e

###
POST http://localhost:5000/pemilik
Content-Type: application/json

{
    "nama": "Yanuar Fauzan",
    "email": "yanuarisnain017@gmail.com",
    "alamat": "bumi"
}

###
PATCH http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e
Content-Type: application/json

{
    "nama": "Yanuar Fauzan",
    "email": "yanuarisnain017@gmail.com",
    "alamat": "bumi kita berdua"
}

###
DELETE http://localhost:5000/pemilik/6484e4fecc424b170c0dcd0e


###
GET http://localhost:5000/penyewa

###
GET http://localhost:5000/penyewa/64855daaab5872a9c1403914

###
POST http://localhost:5000/penyewa
Content-Type: application/json

{
    "nik": "123456789",
    "nama": "yanuar fauzan isnain",
    "email": "yanuar@gmail.com",
    "alamat": "ciamis",
    "no_telp": "085797227164"
}

###
PATCH http://localhost:5000/penyewa/64855daaab5872a9c1403914
Content-Type: application/json

{
    "nik": "123456789",
    "nama": "Anisa Galih Tanzani",
    "email": "anisa@gmail.com",
    "alamat": "ciamis",
    "no_telp": "085797227164"
}

###
DELETE http://localhost:5000/penyewa/64855e21ab5872a9c140391b